name: openclam
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - jupyter
  - ipykernel
  - matplotlib
  - streamlit
  - lxml
  - html5lib
  - beautifulsoup4
  - pip:
      - yfinance
      - requests
      - openai
      - google-genai
      - google-cloud-aiplatform
      - python-dotenv
      - pytest
