name: openclam
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pandas
  - numpy
  - jupyter
  - ipykernel
  - matplotlib
  - pip:
      - yfinance
      - requests
      - openai
      - python-dotenv
      - pytest
